### ISSUE TITLE
Session abnormally terminated

### ISSUE THREAD

**Issue by dicastro** [dceoy/rstudio-server-docker#1]
Hi,

I have tried your image and I have the following issue. I create a container with this command:

```
docker volume create rstudio-server-data
docker container run --rm --name rstudio-server -p 8787:8787 -v rstudio-server-data:/home/rstudio -w /home/rstudio -d dceoy/rstudio-server:slim
```

Server starts correctly and I can login into RStudio Server. The issue is after stoping the container and creating a new one (without creaning the volume). I get this error:

```
The previous R session was abnormally terminated due to an unexpected crash.
You may have lost workspace data as a result of this crash.

[rsession-rstudio] ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:563
```

Have you experienced this issue? Do you know what is that error? Do you have a solution?

I would like to be able to login after stopping and starting the container, and __continue with the session as it was__

If I restart a new session or if I clear all the data, the error disappears, but for me this is not a solution.

**Comment by dceoy** [comment]
You can avoid the error by quitting an R session (with the following orange power button on the navbar).
![2018-10-06 06 29 41](https://user-images.githubusercontent.com/1938249/46561209-b14d1700-c931-11e8-9807-d1507cc93667.png)

**Comment by gacolitti** [comment]
I can confirm that quitting the R session resolves the error experienced when opening a second container that has the rstudio data mapped via a volume. 

I was mapping /.config/rstudio and /.local/share/rstudio (RServer v1.4+) into the container. If you only care about saving settings such as the theme, pane layout, etc., then I believe you can just map /.config/rstudio and remove /.rstudio/monitored--which stores information such as open tabs and last project open. This resolved the issue for me.
