### ISSUE TITLE
content of current.ver URL in Dockerfile not uptodate

### ISSUE THREAD

**Issue by hteuscher** [dceoy/rstudio-server-docker#5]
Hi,
the content of current.ver (https://s3.amazonaws.com/rstudio-server/current.ver) seems to be not uptodate.
I have to replace the download url in dockerfile with static content as workaround:

RUN set -eo pipefail \
      && ln -s /dev/stdout /var/log/syslog \
      && cut -f 1 -d - /tmp/ver \
        | xargs -i curl -SL \
          **https://download2.rstudio.org/server/bionic/amd64/rstudio-server-2021.09.0-351-amd64.deb \**
          -o /tmp/rstudio.deb \
      && apt-get -y install /tmp/rstudio.deb \
      && rm -rf /tmp/rstudio.deb /tmp/ver

best regards
Henrik

**Comment by dceoy** [comment]
I had fixed it at fc8a293c71f700df0398af4d80a97e93815704f0.
